export const GET_ALL_DISPLAYS = 'GET_ALL_DISPLAYS';
export const GET_ALL_DISPLAYS_SUCCESS = 'GET_ALL_DISPLAYS_SUCCESS';
export const GET_ALL_DISPLAYS_ERROR = 'GET_ALL_DISPLAYS_ERROR';

export const SELECT_DISPLAY = 'SELECT_DISPLAY';

export const SEND_COMMAND = 'SEND_COMMAND';
export const SEND_COMMAND_SUCCESS = 'SEND_COMMAND_SUCCESS';
export const SEND_COMMAND_ERROR = 'SEND_COMMAND_ERROR';

